"""made enrollments accessible

Revision ID: 344f3288d1b7
Revises: 152cc95787da
Create Date: 2026-03-13 17:53:23.473328

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '344f3288d1b7'
down_revision: Union[str, Sequence[str], None] = '152cc95787da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('enrollments', sa.Column('progress', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('enrollments', 'progress')
    # ### end Alembic commands ###
