"""added new org fields

Revision ID: 35b95495efcd
Revises: a17dd4d4b66e
Create Date: 2026-03-28 11:49:20.414512

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35b95495efcd'
down_revision: Union[str, Sequence[str], None] = 'a17dd4d4b66e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Organisations', sa.Column('website', sa.String(), nullable=True))
    op.add_column('Organisations', sa.Column('logo', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Organisations', 'logo')
    op.drop_column('Organisations', 'website')
    # ### end Alembic commands ###
