"""added org_id to courses

Revision ID: 3d69371205ed
Revises: 75ac3541d995
Create Date: 2026-03-31 18:07:26.304579

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d69371205ed'
down_revision: Union[str, Sequence[str], None] = '75ac3541d995'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('courses_org_id_fkey'), 'courses', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('courses_org_id_fkey'), 'courses', 'Organisations', ['org_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
