"""added scheme color

Revision ID: 524d62d7f2f7
Revises: 60ef93bc27a4
Create Date: 2026-04-01 23:57:03.197738

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '524d62d7f2f7'
down_revision: Union[str, Sequence[str], None] = '60ef93bc27a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Organisations', sa.Column('theme_color', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Organisations', 'theme_color')
    # ### end Alembic commands ###
