"""added some course fields

Revision ID: 594e03be648b
Revises: 524d62d7f2f7
Create Date: 2026-04-03 00:10:16.805606

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '594e03be648b'
down_revision: Union[str, Sequence[str], None] = '524d62d7f2f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('teacher_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'courses', 'user', ['teacher_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'courses', type_='foreignkey')
    op.drop_column('courses', 'teacher_id')
    # ### end Alembic commands ###
