"""added org id to courses

Revision ID: 60c52736374a
Revises: ad556a6e88a0
Create Date: 2026-03-29 17:42:31.832501

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60c52736374a'
down_revision: Union[str, Sequence[str], None] = 'ad556a6e88a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('org_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'courses', 'Organisations', ['org_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'courses', type_='foreignkey')
    op.drop_column('courses', 'org_id')
    # ### end Alembic commands ###
