"""added role column to orgmembers table

Revision ID: 60ef93bc27a4
Revises: 5c50c3fda5b5
Create Date: 2026-03-31 19:07:02.201868

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60ef93bc27a4'
down_revision: Union[str, Sequence[str], None] = '5c50c3fda5b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('OrganisationMembers', sa.Column('role', sa.String(), nullable=False))
    op.create_foreign_key(None, 'courses', 'Organisations', ['org_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'courses', type_='foreignkey')
    op.drop_column('OrganisationMembers', 'role')
    # ### end Alembic commands ###
