"""Fixed modules and courses

Revision ID: 6d5f534bb73a
Revises: 5e342727d6ce
Create Date: 2026-04-06 18:20:16.388624

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6d5f534bb73a'
down_revision: Union[str, Sequence[str], None] = '5e342727d6ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lessons', sa.Column('type', sa.String(), nullable=False))
    op.add_column('lessons', sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.alter_column('lessons', 'order_index',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               existing_nullable=False,
               postgresql_using='order_index::integer')
    op.drop_column('lessons', 'content_url')
    op.drop_column('lessons', 'content_body')
    op.alter_column('modules', 'order_index',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               existing_nullable=False,
               postgresql_using='order_index::integer')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('modules', 'order_index',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.add_column('lessons', sa.Column('content_body', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('lessons', sa.Column('content_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.alter_column('lessons', 'order_index',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_column('lessons', 'content')
    op.drop_column('lessons', 'type')
    # ### end Alembic commands ###
