"""created plans table

Revision ID: a594306cef44
Revises: 60c52736374a
Create Date: 2026-03-29 18:16:59.235493

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a594306cef44'
down_revision: Union[str, Sequence[str], None] = '60c52736374a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('max_members', sa.Integer(), nullable=True),
    sa.Column('max_courses', sa.Integer(), nullable=True),
    sa.Column('features', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_plans_id'), 'plans', ['id'], unique=False)
    op.add_column('Organisations', sa.Column('plan_id', sa.UUID(), nullable=True))
    op.add_column('Organisations', sa.Column('plan_expires_at', sa.DateTime(timezone=True), nullable=True))
    op.create_foreign_key(None, 'Organisations', 'plans', ['plan_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Organisations', type_='foreignkey')
    op.drop_column('Organisations', 'plan_expires_at')
    op.drop_column('Organisations', 'plan_id')
    op.drop_index(op.f('ix_plans_id'), table_name='plans')
    op.drop_table('plans')
    # ### end Alembic commands ###
