"""fixed course category relf

Revision ID: a967404df20e
Revises: 7dad6a5d0c62
Create Date: 2025-12-13 02:19:51.072152

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a967404df20e'
down_revision: Union[str, Sequence[str], None] = '7dad6a5d0c62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('category_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'courses', 'categories', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('enrollments', 'course_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(None, 'courses', type_='foreignkey')
    op.drop_column('courses', 'category_id')
    # ### end Alembic commands ###
