"""add logo and created_at to organisations

Revision ID: ad556a6e88a0
Revises: 35b95495efcd
Create Date: 2026-03-28 16:18:39.243107

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad556a6e88a0'
down_revision: Union[str, Sequence[str], None] = '35b95495efcd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Organisations', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Organisations', 'created_at')
    # ### end Alembic commands ###
