"""add_performance_indexes

Revision ID: fbe425c52d15
Revises: af0e069a8c8a
Create Date: 2026-09-09 12:05:05.374047

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fbe425c52d15'
down_revision: Union[str, Sequence[str], None] = 'af0e069a8c8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_OrganisationMembers_organisation_id'), 'OrganisationMembers', ['organisation_id'], unique=False)
    op.create_index('ix_org_members_org_role', 'OrganisationMembers', ['organisation_id', 'role'], unique=False)
    op.create_index(op.f('ix_Organisations_owner_id'), 'Organisations', ['owner_id'], unique=False)
    op.create_index(op.f('ix_channel_members_user_id'), 'channel_members', ['user_id'], unique=False)
    op.create_index('ix_connections_addressee_status', 'connections', ['addressee_id', 'status'], unique=False)
    op.create_index('ix_connections_requester_status', 'connections', ['requester_id', 'status'], unique=False)
    op.create_index(op.f('ix_courses_admin_id'), 'courses', ['admin_id'], unique=False)
    op.create_index(op.f('ix_courses_category_id'), 'courses', ['category_id'], unique=False)
    op.create_index(op.f('ix_courses_org_id'), 'courses', ['org_id'], unique=False)
    op.create_index(op.f('ix_courses_teacher_id'), 'courses', ['teacher_id'], unique=False)
    op.create_index(op.f('ix_device_tokens_user_id'), 'device_tokens', ['user_id'], unique=False)
    op.create_index('ix_enrollments_course_completed', 'enrollments', ['course_id', 'completed_at'], unique=False)
    op.create_index(op.f('ix_enrollments_course_id'), 'enrollments', ['course_id'], unique=False)
    op.create_index(op.f('ix_flashcards_material_id'), 'flashcards', ['material_id'], unique=False)
    op.create_index(op.f('ix_flashcards_user_id'), 'flashcards', ['user_id'], unique=False)
    op.create_index('ix_flashcards_user_next_review', 'flashcards', ['user_id', 'next_review_date'], unique=False)
    op.create_index('ix_invitations_org_email', 'invitations', ['organisation_id', 'target_email'], unique=False)
    op.create_index('ix_invitations_org_expires', 'invitations', ['organisation_id', 'expires_at'], unique=False)
    op.create_index(op.f('ix_invitations_organisation_id'), 'invitations', ['organisation_id'], unique=False)
    op.create_index('ix_lesson_progress_course_id', 'lesson_progress', ['course_id'], unique=False)
    op.create_index('ix_lesson_progress_student_course', 'lesson_progress', ['student_id', 'course_id'], unique=False)
    op.create_index('ix_lesson_progress_student_lesson', 'lesson_progress', ['student_id', 'lesson_id'], unique=False)
    op.create_index(op.f('ix_lessons_module_id'), 'lessons', ['module_id'], unique=False)
    op.create_index('ix_messages_channel_created_at', 'messages', ['channel_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_messages_channel_id'), 'messages', ['channel_id'], unique=False)
    op.create_index(op.f('ix_modules_course_id'), 'modules', ['course_id'], unique=False)
    op.create_index(op.f('ix_playlist_courses_course_id'), 'playlist_courses', ['course_id'], unique=False)
    op.create_index(op.f('ix_playlist_enrollments_playlist_id'), 'playlist_enrollments', ['playlist_id'], unique=False)
    op.create_index(op.f('ix_playlist_enrollments_student_id'), 'playlist_enrollments', ['student_id'], unique=False)
    op.create_index('ix_playlist_enrollments_student_playlist', 'playlist_enrollments', ['student_id', 'playlist_id'], unique=False)
    op.create_index(op.f('ix_playlists_creator_id'), 'playlists', ['creator_id'], unique=False)
    op.create_index(op.f('ix_playlists_org_id'), 'playlists', ['org_id'], unique=False)
    op.create_index(op.f('ix_questions_material_id'), 'questions', ['material_id'], unique=False)
    op.create_index(op.f('ix_questions_user_id'), 'questions', ['user_id'], unique=False)
    op.create_index(op.f('ix_study_materials_user_id'), 'study_materials', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_study_materials_user_id'), table_name='study_materials')
    op.drop_index(op.f('ix_questions_user_id'), table_name='questions')
    op.drop_index(op.f('ix_questions_material_id'), table_name='questions')
    op.drop_index(op.f('ix_playlists_org_id'), table_name='playlists')
    op.drop_index(op.f('ix_playlists_creator_id'), table_name='playlists')
    op.drop_index('ix_playlist_enrollments_student_playlist', table_name='playlist_enrollments')
    op.drop_index(op.f('ix_playlist_enrollments_student_id'), table_name='playlist_enrollments')
    op.drop_index(op.f('ix_playlist_enrollments_playlist_id'), table_name='playlist_enrollments')
    op.drop_index(op.f('ix_playlist_courses_course_id'), table_name='playlist_courses')
    op.drop_index(op.f('ix_modules_course_id'), table_name='modules')
    op.drop_index(op.f('ix_messages_channel_id'), table_name='messages')
    op.drop_index('ix_messages_channel_created_at', table_name='messages')
    op.drop_index(op.f('ix_lessons_module_id'), table_name='lessons')
    op.drop_index('ix_lesson_progress_student_lesson', table_name='lesson_progress')
    op.drop_index('ix_lesson_progress_student_course', table_name='lesson_progress')
    op.drop_index('ix_lesson_progress_course_id', table_name='lesson_progress')
    op.drop_index(op.f('ix_invitations_organisation_id'), table_name='invitations')
    op.drop_index('ix_invitations_org_expires', table_name='invitations')
    op.drop_index('ix_invitations_org_email', table_name='invitations')
    op.drop_index('ix_flashcards_user_next_review', table_name='flashcards')
    op.drop_index(op.f('ix_flashcards_user_id'), table_name='flashcards')
    op.drop_index(op.f('ix_flashcards_material_id'), table_name='flashcards')
    op.drop_index(op.f('ix_enrollments_course_id'), table_name='enrollments')
    op.drop_index('ix_enrollments_course_completed', table_name='enrollments')
    op.drop_index(op.f('ix_device_tokens_user_id'), table_name='device_tokens')
    op.drop_index(op.f('ix_courses_teacher_id'), table_name='courses')
    op.drop_index(op.f('ix_courses_org_id'), table_name='courses')
    op.drop_index(op.f('ix_courses_category_id'), table_name='courses')
    op.drop_index(op.f('ix_courses_admin_id'), table_name='courses')
    op.drop_index('ix_connections_requester_status', table_name='connections')
    op.drop_index('ix_connections_addressee_status', table_name='connections')
    op.drop_index(op.f('ix_channel_members_user_id'), table_name='channel_members')
    op.drop_index(op.f('ix_Organisations_owner_id'), table_name='Organisations')
    op.drop_index('ix_org_members_org_role', table_name='OrganisationMembers')
    op.drop_index(op.f('ix_OrganisationMembers_organisation_id'), table_name='OrganisationMembers')
    # ### end Alembic commands ###
